name:                codec-util
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/codec-util#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - iconv
  - bytestring
  - charsetdetect

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

tests:
  doctest:
    cpp-options: -DTEST
    main: Doctest
    source-dirs:
      - test
      - src
    dependencies:
      - doctest